#!/bin/zsh

# Package Generator Utility for lie CLI Framework

package_from_config() {
    local module_name="$1"
    if [ -z "$module_name" ]; then
        echo -e "${RED}Error: Please specify a module name${NC}"
        echo "Usage: lie package <module-name>"
        exit 1
    fi
    
    local config_file="${module_name}.json"
    if [ ! -f "$config_file" ]; then
        echo -e "${RED}Error: Config file '$config_file' not found${NC}"
        echo "Create it first with: lie create $module_name"
        exit 1
    fi
    
    echo -e "${BLUE}Generating CLI package from config: $config_file${NC}"
    echo ""
    
    # Parse JSON config (simple parsing)
    local module_description=$(grep '"description"' "$config_file" | sed 's/.*"description": *"\([^"]*\)".*/\1/')
    local module_alias=$(grep '"alias"' "$config_file" | sed 's/.*"alias": *"\([^"]*\)".*/\1/')
    
    local cli_dir="${module_name}_cli"
    local commands_file="$cli_dir/commands.sh"
    local cli_internal_dir="$cli_dir/.cli"
    
    # Remove existing CLI directory if it exists
    if [ -d "$cli_dir" ]; then
        rm -rf "$cli_dir"
    fi
    
    # Create CLI directory structure
    mkdir -p "$cli_internal_dir"
    
    # Generate commands.sh with basic function stubs
    cat > "$commands_file" <<EOF
#!/bin/zsh

# Commands for $module_name module
# Generated from $config_file
# Define your subcommand functions here

EOF
    
    # Extract all command names from JSON and generate function stubs
    # Look for command names within the commands array
    awk '/"commands": \[/,/^\s*\]/' "$config_file" | grep '"name"' | sed 's/.*"name": *"\([^"]*\)".*/\1/' | while read -r cmd_name; do
        cat >> "$commands_file" <<EOF
$cmd_name() {
    print_info "Running $cmd_name..."
    # Your $cmd_name logic here
    print_success "$cmd_name completed!"
}

EOF
    done
    
    cat >> "$commands_file" <<EOF
help() {
    print_info "Available commands:"
EOF
    
    # Add help entries for each command
    awk '/"commands": \[/,/^\s*\]/' "$config_file" | grep '"name"' | sed 's/.*"name": *"\([^"]*\)".*/\1/' | while read -r cmd_name; do
        echo "    print_info \"  $cmd_name   - Run $cmd_name command\"" >> "$commands_file"
    done
    
    cat >> "$commands_file" <<EOF
    print_info "  help    - Show this help message"
}
EOF
    
    chmod +x "$commands_file"
    
    # Create the main module script
    local module_script="$cli_internal_dir/$module_name.sh"
    cat > "$module_script" <<EOF
#!/bin/zsh

# Module: $module_name
# Generated by lie CLI Framework from config

LIE_HOME="\${LIE_HOME:-\$HOME/.lie}"
source "\$LIE_HOME/utils/common.sh"

MODULE_NAME="$module_name"
MODULE_VERSION="1.0.0"
MODULE_DESCRIPTION="$module_description"

# Source user commands
CLI_DIR="\$(dirname "\$0")"
source "\$CLI_DIR/commands.sh"

show_help() {
    echo -e "\${BLUE}\$MODULE_NAME v\$MODULE_VERSION\${NC}"
    echo "Description: \$MODULE_DESCRIPTION"
    echo ""
    echo "Usage: \$MODULE_NAME <subcommand>"
    echo ""
    echo "Subcommands:"
EOF
    
    # Add help entries for each command
    awk '/"commands": \[/,/^\s*\]/' "$config_file" | grep '"name"' | sed 's/.*"name": *"\([^"]*\)".*/\1/' | while read -r cmd_name; do
        echo "    echo \"  $cmd_name   - Run $cmd_name command\"" >> "$module_script"
    done
    
    cat >> "$module_script" <<EOF
    echo "  help    - Show this help message"
}

show_status() {
    echo -e "\${BLUE}Status for \$MODULE_NAME\${NC}"
    echo "Module: \$MODULE_NAME"
    echo "Version: \$MODULE_VERSION"
    echo "Commands file: \$CLI_DIR/commands.sh"
}

execute_subcommand() {
    local subcommand="\$1"
    shift
    
    case \$subcommand in
        help|--help|-h)
            help
            ;;
        status)
            show_status
            ;;
EOF
    
    # Add case entries for each command
    awk '/"commands": \[/,/^\s*\]/' "$config_file" | grep '"name"' | sed 's/.*"name": *"\([^"]*\)".*/\1/' | while read -r cmd_name; do
        echo "        $cmd_name)" >> "$module_script"
        echo "            # Execute the function with remaining arguments" >> "$module_script"
        echo "            \"\$subcommand\" \"\$@\"" >> "$module_script"
        echo "            ;;" >> "$module_script"
    done
    
    cat >> "$module_script" <<EOF
        *)
            echo -e "\${RED}Error: Unknown subcommand '\$subcommand'\${NC}"
            echo ""
            show_help
            exit 1
            ;;
    esac
}

main() {
    if [ \$# -eq 0 ]; then
        show_help
        exit 0
    fi
    
    execute_subcommand "\$@"
}

main "\$@"
EOF
    
    chmod +x "$module_script"
    
    # Create install script
    local install_script="$cli_dir/install.sh"
    cat > "$install_script" <<EOF
#!/bin/zsh

# Install script for $module_name CLI
LIE_HOME="\${LIE_HOME:-\$HOME/.lie}"
MODULES_DIR="\$LIE_HOME/modules"
BIN_DIR="\$HOME/.local/bin"

echo "Installing $module_name CLI..."

# Create module directory
mkdir -p "\$MODULES_DIR/$module_name"

# Copy module script and commands
cp ".cli/$module_name.sh" "\$MODULES_DIR/$module_name/"
cp "commands.sh" "\$MODULES_DIR/$module_name/"

EOF
    
    # Add alias creation if specified
    if [ -n "$module_alias" ]; then
        cat >> "$install_script" <<EOF
# Create alias if specified
if [ -n "$module_alias" ]; then
    mkdir -p "\$BIN_DIR"
    cat > "\$BIN_DIR/$module_alias" <<'ALIAS_EOF'
#!/bin/zsh
"\$HOME/.lie/modules/$module_name/$module_name.sh" "\$@"
ALIAS_EOF
    chmod +x "\$BIN_DIR/$module_alias"
    echo "Created alias: $module_alias"
fi

EOF
    fi
    
    cat >> "$install_script" <<EOF
echo "✅ $module_name CLI installed successfully!"
if [ -n "$module_alias" ]; then
    echo "Run '$module_alias help' to see available commands"
else
    echo "Run 'lie $module_name help' to see available commands"
fi
EOF
    
    chmod +x "$install_script"
    
    echo -e "${GREEN}✅ Generated CLI package: $cli_dir${NC}"
    echo ""
    echo -e "${BLUE}Structure created:${NC}"
    echo "  $cli_dir/"
    echo "  ├── commands.sh     (edit this to add your logic)"
    echo "  ├── install.sh      (run this to install)"
    echo "  └── .cli/           (framework files - don't touch)"
    echo ""
    echo -e "${BLUE}Next steps:${NC}"
    echo "  1. Edit $cli_dir/commands.sh to add your subcommand logic"
    echo "  2. Run ./$cli_dir/install.sh to install the module"
    if [ -n "$module_alias" ]; then
        echo "  3. Test with: $module_alias help"
    else
        echo "  3. Test with: lie $module_name help"
    fi
} 